name = "healthymeal"
compatibility_date = "2024-12-10"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "dist"

[vars]
NODE_ENV = "production"

[[kv_namespaces]]
binding = "SESSION"
id = "session"
preview_id = "session" 