name = "healthymeal"
compatibility_date = "2024-12-10"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

pages_build_output_dir = "dist"

[vars]
NODE_ENV = "production" 