name = "healthymeal"
compatibility_date = "2024-12-10"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "dist"

[vars]
NODE_ENV = "production"
# These will be overridden by Cloudflare Pages environment variables
SUPABASE_URL = "placeholder"
SUPABASE_KEY = "placeholder"
OPENROUTER_API_KEY = "placeholder" 